version: '3.9'

services:
  backend:
    build:
      context: ./rsi_service
    container_name: backend-app
    ports:
      - "4000:4000"

  frontend:
    build:
      context: ./frontend
    container_name: frontend-app
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:4000
    depends_on:
      - backend
