version: '3.9'

services:
  frontend:
    build: ../frontend
    ports:
      - "3000:3000"

  rsi_service:
    build: ../rsi_service
    ports:
      - "5000:5000"

  ingestion:
    build: ../ingestion